# Production environment values
replicaCount: 3

image:
  tag: "v1.0.0" # Use specific version in production

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
  - host: oauth2.example.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: oauth2-server-tls
    hosts:
    - oauth2.example.com

config:
  server:
    baseUrl: "https://oauth2.example.com"
  # JWT secret should be set via external secret management

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 2

persistence:
  enabled: true
  storageClass: "fast-ssd"
  size: 10Gi

healthCheck:
  enabled: true

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - oauth2-server
        topologyKey: kubernetes.io/hostname
