version: '3.8'

services:
  oauth2-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PUBLIC_BASE_URL=http://localhost:8080
      - PORT=8080
      - TEST_USER_USERNAME=john.doe
      - TEST_USER_PASSWORD=password123
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=oauth2_server
      - POSTGRES_USER=oauth2_user
      - POSTGRES_PASSWORD=your-db-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: