{{- if .Values.config.jwt.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-server.fullname" . }}-secret
  labels:
    {{- include "oauth2-server.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.config.jwt.secret | b64enc }}
{{- end }}